import { lazy } from 'react'

// 页面统一延迟加载，避免首屏打包 ECharts、lightweight-charts 等重依赖。
export const Watchlist = lazy(() => import('./Watchlist').then(module => ({ default: module.Watchlist })))
export const Screener = lazy(() => import('./Screener').then(module => ({ default: module.Screener })))
export const Backtest = lazy(() => import('./Backtest').then(module => ({ default: module.Backtest })))
export const Financials = lazy(() => import('./Financials').then(module => ({ default: module.Financials })))
export const Data = lazy(() => import('./Data').then(module => ({ default: module.Data })))
export const Monitor = lazy(() => import('./Monitor').then(module => ({ default: module.Monitor })))
export const Dashboard = lazy(() => import('./Dashboard').then(module => ({ default: module.Dashboard })))
export const UsMarketDashboard = lazy(() => import('./UsMarketDashboard').then(module => ({ default: module.UsMarketDashboard })))
export const StockPortfolio = lazy(() => import('./StockPortfolio').then(module => ({ default: module.StockPortfolio })))
export const FundPortfolio = lazy(() => import('./FundPortfolio').then(module => ({ default: module.FundPortfolio })))
export const AnalysisDetail = lazy(() => import('./AnalysisDetail').then(module => ({ default: module.AnalysisDetail })))
export const ConceptAnalysis = lazy(() => import('./ConceptAnalysis').then(module => ({ default: module.ConceptAnalysis })))
export const IndustryAnalysis = lazy(() => import('./IndustryAnalysis').then(module => ({ default: module.IndustryAnalysis })))
export const LeadingSector = lazy(() => import('./LeadingSector').then(module => ({ default: module.LeadingSector })))
export const InvestmentExpert = lazy(() => import('./InvestmentExpert').then(module => ({ default: module.InvestmentExpert })))
export const StockAnalysis = lazy(() => import('./StockAnalysis').then(module => ({ default: module.StockAnalysis })))
export const Review = lazy(() => import('./Review').then(module => ({ default: module.Review })))
export const LimitUpLadder = lazy(() => import('./LimitUpLadder').then(module => ({ default: module.LimitUpLadder })))
export const Branding = lazy(() => import('./Branding').then(module => ({ default: module.Branding })))
export const Settings = lazy(() => import('./Settings').then(module => ({ default: module.Settings })))
export const Indices = lazy(() => import('./Indices').then(module => ({ default: module.Indices })))
export const Regime = lazy(() => import('./Regime').then(module => ({ default: module.Regime })))
export const Dev = lazy(() => import('./Dev').then(module => ({ default: module.Dev })))
